name: Update Q&A

on:
  workflow_dispatch:
    inputs:
      question:
        description: 'Question'
        required: true
      answer:
        description: 'Answer'
        required: true

jobs:
  update-qa:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Add new Q&A
        run: |
          QUESTION="${{ github.event.inputs.question }}"
          ANSWER="${{ github.event.inputs.answer }}"
          echo "Adding new Q&A: $QUESTION - $ANSWER"
          # Fetch the latest data.json
          git pull
          # Decode the data.json file
          DATA=$(cat data.json | base64 --decode)
          # Add new question and answer
          NEW_DATA=$(echo "$DATA" | jq ". += [{\"question\": \"$QUESTION\", \"answer\": \"$ANSWER\"}]")
          # Encode and update data.json
          echo "$NEW_DATA" | base64 > data.json
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add data.json
          git commit -m "Add new Q&A: $QUESTION"
          git push
    env:
      GITHUB_TOKEN: ${{ secrets.QANDATOKEN }}
